chore(test: need to initialize 8 pumps, while increment Class member during __init__) Used self instead of Class Motors for the atexit.  (This is getting annoying.)
Small typos.  (long list of errors.)

Forcing a float because of this error:
my_thread = ThreadMe(self.motor, ounces * self.calibration, self.name)
TypeError: can't multiply sequence by non-int of type 'float'
Also, atexit had some definition issues due to scope.  Hopefully fixed.

Just took out the Normalized line.  Got too complicaed to fix it.  Don't need it anymore.

There is no calibration list anymore.  Took that out.  Handled within the Motors Class now.

Slight typo -- broken line

Small change, looping now through 8 pumps!  W00t!

Another small typo: forgot to specify the Class member.

Small typo -- initializing the pump to 0 since it increments before using,
but then I *did* use it before incrementing, so instead, I used None.
I don't really like that solution.  But will clean it up later. (Yeah right. j/k)

First try at my sneaky plan!  Cross fingers!

Was:
I'm hoping to increment through all the motors as each is initialized.
Kinda sneaky. :)